export const SITE_NAME = "Hiroom.Blog"
export const HOME_URL = "https://hiroomblog.com"
export const HOME_IMAGE_URL = "/assets/home/cover.webp"
export const HOME_DESCRIPTION = "This is a personal blog, Hiro's room! I will share my experience or thoughts about mainly work as a product manager in the Internet industory."
export const ABOUT_DESCRIPTION = "Hello! I am Hiroki, a product manager focusing on software engineering and data science."
