export const SITE_NAME = "Hiroom.Blog"
export const HOME_URL = "https://hiroomblog.com"
export const HOME_IMAGE_URL = "/assets/home/cover.webp"
export const HOME_DESCRIPTION = "This is a personal blog, Hiro's room! It stores my experience as a product manager."
export const ABOUT_DESCRIPTION = "Hi there! My name is Hiroki. I am a product manager at the largest e-commerce company in Japan."
