export const SITE_NAME = "Hiroom.Blog"
export const HOME_URL = "https://hiroomblog.com"
export const HOME_IMAGE_URL = "/assets/home/cover.webp"
export const HOME_DESCRIPTION = "This is a personal blog, Hiro's room! I am sharing my experience or thoughts mainly about work as a product manager in tech."
export const ABOUT_DESCRIPTION = "Hello! I am Hiroki, a product manager focusing on data science and software engineering. Here's about me!"
